spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todoDB
    username: root
    password: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      ddl-auto: update
    show-sql: true